---
- hosts: node1
  become: true
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ../docker-compose.yml
      dest: /home/vagrant
      owner: vagrant
      group: vagrant
      mode: '0777'
  - name: Create bash script file
    ansible.builtin.shell:
      cmd: echo -n "sudo " > /home/vagrant/worker.sh
  - name: Create docker-swarm manager
    ansible.builtin.shell:
      cmd: docker swarm init --advertise-addr 172.16.1.50 | awk "NR==5" | awk '{ for (i=1; i<=NF; i++) printf "%s ", $i; printf "\n" }' >> /home/vagrant/worker.sh
  - name: Send a script file to a manage
    fetch:
      src: ./worker.sh
      dest: ./ 
- hosts: node2
  become: true
  tasks:
  - name: Transfer the script
    copy: src=./node1/worker.sh dest=/home/vagrant/ mode=0777
  - name: Execute the script
    command: bash /home/vagrant/worker.sh
- hosts: node1
  become: true
  tasks:
  - name: Deploy the project
    ansible.builtin.shell:
      cmd: docker stack deploy -c /home/vagrant/docker-compose.yml my-stack
